### ISSUE TITLE
Problem with mouse interaction

### ISSUE THREAD

**Issue by nebrekab** [CreateJS/CreateJS#5]
**Issue**
In Firefox and MS Edge on PC, mouse interaction does not work properly. In Chrome everything works fine. This could be to do with running on Parallels for Mac.

In our games where we add a button, its click event is triggered by the whole stage being clicked and not the button itself.  

**Examples**
Here's a basic codepen example: https://codepen.io/nebrekab/pen/MNGKoo

The same seems to happen on the CreateJS examples:

Flower drag and drop on live site
https://createjs.com/demos/easeljs/draganddrop

Banana drag and drop on codepen
https://codepen.io/createjs/pen/VQrvGN

**Versions**
Browsers with issue: 
- Firefox 68.0.1 (64-bit)
- Microsoft Edge 42.17134.1.0, IE 11.523.171...

CreateJS v1.0.0 - https://code.createjs.com/1.0.0/createjs.min.js
Parallels Version 14.1.3 (45485) -  https://www.parallels.com/
OSX 10.14.6 Mojave

**Status**
Following up with the Parallels team, but any thoughts on the issue would be super helpful :)

**Comment by nebrekab** [comment]
**Update**
This seems to either be specific to **32-bit** versions of these browsers and/or the fact I am running within a a virtual machine on a Mac (Parallels).

**Comment by nebrekab** [comment]
**Fixed**
Parallels 15 has now been released and fixed the issue and MS Edge & Firefox mouse interaction now works as expected.

**Comment by eternal-sorrow** [comment]
I still have this problem, Firefox 146, Linux.

**Comment by eternal-sorrow** [comment]
Updating cratejs in the codepen to https://cdn.jsdelivr.net/npm/createjs@1.0.1/builds/1.0.0/createjs.min.js doesn't fix the issue.
